<a href="https://colab.research.google.com/github/gurwoghd/2023_WFK_ICT-Jordan-/blob/main/sourcecodes/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# FILE HANDLING

In [ ]:
file_path = '/content/drive/MyDrive/Jordan_edu/hello.txt' # cf) file_path can be varied.
# you have to find the path to the file in your drive or computer.

f=open(file_path, 'r')

In [ ]:
f.close()

In [ ]:
with open(file_path, 'w') as f:
  f.write('hello\n')
  f.writelines(['a','b','k']) # abk

In [ ]:
f = open(file_path, 'r')

In [ ]:
str1=f.read(3)
str1

'hel'

In [ ]:
f.tell()

3

In [ ]:
str2 = f.readline()
str2

'lo\n'

In [ ]:
f.tell()

6

In [ ]:
f.seek(0)

0

In [ ]:
f.readlines()

['hello\n', 'abk']

In [ ]:
f.tell()

9

In [ ]:
f.close()

# USING LIABRARY

## math module

### first way to import math module

In [ ]:
import math
math.pow(2,4)

16.0

In [ ]:
math.sqrt(5)

2.23606797749979

### second way to import math module

In [ ]:
import math as m

In [ ]:
m.pow(2,4)

16.0

In [ ]:
m.sqrt(5)

2.23606797749979

### third way to import math module

In [ ]:
from math import pow, sqrt

In [ ]:
pow(2,4)

16.0

In [ ]:
sqrt(5)

2.23606797749979

### forth way to import math module

In [ ]:
from math import pow as p, sqrt as s

In [ ]:
p(2,4)

16.0

In [ ]:
s(5)

2.23606797749979

### Lab
try printing square root of input data (data type is int)

In [ ]:
import math

a = int(input())
print('The square root of', a, 'is',math.sqrt(a))

14
The square root of 14 is 3.7416573867739413


## random module

In [2]:
import random

In [3]:
random.random() # this returns float between 0 and 1

0.5226425055368724

In [7]:
random.uniform(2,4)

3.847501484263841

In [ ]:
random.randint(2,4)

4

In [ ]:
random.randrange(1,7,1)

2

In [ ]:
seq = [1,2,3,4,5,6]
random.choice(seq)

1

In [ ]:
random.shuffle(seq)
seq

[4, 2, 5, 3, 6, 1]

### rock scissors paper

In [ ]:
import random

rsp = ['rock', 'scissors', 'paper']

while True:
  data = int(input("rock scissors paper!! (1: rock, 2: scissor, 3:paper) => "))

  com_data = random.randint(1,3)
  if data == 1 and com_data == 2:
    print('you win!! you: ', rsp[data-1], 'com: ', rsp[com_data-1])
    break
  elif data == 2 and com_data == 3:
    print('you win!! you: ', rsp[data-1], 'com: ', rsp[com_data-1])
    break
  elif data == 3 and com_data == 1:
    print('you win!! you: ', rsp[data-1], 'com: ', rsp[com_data-1])
    break
  else:
    print('you: ', rsp[data-1], 'com: ', rsp[com_data-1])


rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 1
you:  rock com:  rock
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 2
you:  scissors com:  rock
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  paper
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  paper
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  paper
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  paper
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  paper
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you:  paper com:  scissors
rock scissors paper!! (1: rock, 2: scissor, 3:paper) => 3
you win!! you:  paper com:  rock


### Lab
making a lottery machine

In [ ]:
import math
import random

In [ ]:
money = 10000
cost = 1000
again = 1

answer = []

while again and (money >= cost):
  money -= cost
  for i in range(7):
    answer.append(random.randint(1,11))
  user_ball = map(int, input('input your guess =>').split())
  if user_ball == answer:
    print('you won!!!')
  else:
    print('The answer was', answer)
    print('Do you want to do it again?(cost:1000, remaining money: {})\n'.format(money))
    again = int(input('(1: yes, 0: no) => '))

print('remaining money:', money)


input your guess =>1 2 3 4 5 6 7
The answer was [7, 2, 1, 11, 8, 7, 6]
Do you want to do it again?(cost:1000, remaining money: 9000)

(1: yes, 0: no) => 0
remaining money: 9000


# numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a[0,0]

0

In [ ]:
a[0,:]

array([0, 1, 2])

In [ ]:
a[0,0:2]

array([0, 1])

In [ ]:
b=np.array([0,1,2]) * 10
b

array([ 0, 10, 20])

In [ ]:
idx1 = np.array([True, False, True])

In [ ]:
print(b[idx1])

[ 0 20]


In [ ]:
c=np.array([0,1,2,3,4,5,6,7]) * 10
idx2 = np.array([0,2,3,3,6])
print(c[idx2])

[ 0 20 30 30 60]


In [ ]:
a = a.reshape(3,2)


In [ ]:
d=np.array([[1,2],[3,4],[5,6]])
a_Y = np.concatenate((a,d), axis = 0) # merging vertically
a_Y

array([[0, 1],
       [2, 3],
       [4, 5],
       [1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a_X = np.concatenate((a,d), axis = 1)
a_X

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6]])

In [ ]:

# numpy.split()

e = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [ ]:
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
slice_Y_equal_size = np.split(e, 2, axis = 0)
print(slice_Y_equal_size)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [ ]:
slice_Y_different_size = np.split(e, [2,3], axis = 0)
slice_Y_different_size

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [ ]:
# numpy.sum()

f = np.arange(4*2*4).reshape(4,2,4)

In [ ]:
new_f = np.sum(f)
new_f

496

In [ ]:
np.sum(f[f>10])

441

In [ ]:
np.max(a)

5

In [ ]:
np.min(a)

0

In [ ]:
np.mean(a)

2.5

In [ ]:
np.std(a)

1.707825127659933

## Lab
use numpy.dot()

In [ ]:
A = np.array([1,2,3,4,5,6])
B = np.array([11,12,13,14,15,16])

In [ ]:
A_reshaped = A.reshape(3,2)
B_reshaped = B.reshape(2,3)

In [ ]:
np.dot(A_reshaped, B_reshaped)

array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]])

## Lab
use numpy methods

In [ ]:
import numpy as np

A = np.array([[1,4,5,8],[2,1,7,3],[5,4,5,9]])
B=A.reshape(6,2)
Bsplit = np.split(B, 2, axis=0)
C = Bsplit[0]
D = Bsplit[1]
E = np.concatenate((C,D), axis=1)

# pandas(Series) 실습

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# declare a Series

arr = [1,2,3]
s = pd.Series(arr)
s

0    1
1    2
2    3
dtype: int64

In [ ]:
# change index

arr2 = [100,200,300]
index=['Hong','Hyeok','Jae']
s=pd.Series(arr2, index)
s

Hong     100
Hyeok    200
Jae      300
dtype: int64

In [ ]:
s.index # get indexes

Index(['Hong', 'Hyeok', 'Jae'], dtype='object')

In [ ]:
s.values # get values

array([100, 200, 300])

In [ ]:
print(s.iloc[0]) # type is numpy ndarray
print('-------------------')
print(s.iloc[0:2]) # type is Series
print('-------------------')
print(s.iloc[[0,2]]) # type is Series

100
-------------------
Hong     100
Hyeok    200
dtype: int64
-------------------
Hong    100
Jae     300
dtype: int64


In [ ]:
print(s.loc['Hong']) # type is numpy
print('--------------------')
print(s.loc['Hong':'Jae']) # type is Series
print("--------------------")
print(s.loc[['Hong','Jae']]) # type is Series

100
--------------------
Hong     100
Hyeok    200
Jae      300
dtype: int64
--------------------
Hong    100
Jae     300
dtype: int64


In [ ]:
print(s['Hyeok'])

200


In [ ]:
print(s[0])

100


In [ ]:
# Adding and removing
s.loc['k'] = 400
print(s)

Hong     100
Hyeok    200
Jae      300
k        400
dtype: int64


In [ ]:
s.drop('Hong')

Hyeok    200
Jae      300
k        400
dtype: int64

In [ ]:
s # original is prevented

Hong     100
Hyeok    200
Jae      300
k        400
dtype: int64

In [ ]:
s2 = s.drop(['Hong','Hyeok'])

In [ ]:
s

Hong     100
Hyeok    200
Jae      300
k        400
dtype: int64

In [ ]:
s.drop('k', inplace=True)

In [ ]:
s

Hong     100
Hyeok    200
Jae      300
dtype: int64

In [ ]:
s.drop('Hong', inplace=True)

In [ ]:
s

Hyeok    200
Jae      300
dtype: int64

In [ ]:
# operation

s = s+10
s

Hong     110
Hyeok    210
Jae      310
dtype: int64

In [ ]:
high = pd.Series([1,2,3])
low = pd.Series([-1,-2,-3])
diff = high - low
diff

0    2
1    4
2    6
dtype: int64

In [ ]:
print(s[s>=150])

Hyeok    210
Jae      310
dtype: int64


# pandas(DataFrame) 실습

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr = {'Hong':[1,2,3],
       'Hyeok':[4,5,6],
       'Jae':[7,8,9]
       }
index = ['a','b','c']
df = pd.DataFrame(data=arr, index=index)
print(df)

   Hong  Hyeok  Jae
a     1      4    7
b     2      5    8
c     3      6    9


In [ ]:
print(df['Hong']) # type is Series
print('-----------------')
print(df[['Hong','Hyeok']]) # type is DataFrame

a    1
b    2
c    3
Name: Hong, dtype: int64
-----------------
   Hong  Hyeok
a     1      4
b     2      5
c     3      6


In [ ]:
print(df.loc['a'])
print('-----------------')
print(df.iloc[0])

Hong     1
Hyeok    4
Jae      7
Name: a, dtype: int64
-----------------
Hong     1
Hyeok    4
Jae      7
Name: a, dtype: int64


In [ ]:
print(df.loc['a':'b'])
print('----------------')
print(df.iloc[0:3])

   Hong  Hyeok  Jae
a     1      4    7
b     2      5    8
----------------
   Hong  Hyeok  Jae
a     1      4    7
b     2      5    8
c     3      6    9


In [ ]:
df.iloc[0,1]

4

In [ ]:
df.loc['a','Hong']

1

In [ ]:
df.iloc[[0,1],[0,1]]

Hong  Hyeok
a     1      4
b     2      5

In [ ]:
df.iloc[0:2,0:2]

Hong  Hyeok
a     1      4
b     2      5

In [ ]:
df.loc[['a','c'],['Hong','Jae']]

Hong  Jae
a     1    7
c     3    9

In [ ]:
df.loc['a':'c', 'Hong':'Hyeok']

Hong  Hyeok
a     1      4
b     2      5
c     3      6

In [ ]:
df['cute'] = df['Hong'] - df['Hyeok']
print(df)

   Hong  Hyeok  Jae  cute
a     1      4    7    -3
b     2      5    8    -3
c     3      6    9    -3


In [ ]:
df2 = df.drop('cute', axis=1)

In [ ]:
df2

Hong  Hyeok  Jae
a     1      4    7
b     2      5    8
c     3      6    9

In [ ]:
df

Hong  Hyeok  Jae  cute
a     1      4    7    -3
b     2      5    8    -3
c     3      6    9    -3

In [ ]:
df.loc['d'] = df.loc['a'] - df.loc['c']
df

Hong  Hyeok  Jae  cute
a     1      4    7    -3
b     2      5    8    -3
c     3      6    9    -3
d    -2     -2   -2     0

In [ ]:
df3 = df.drop('a', axis=0)
df3

Hong  Hyeok  Jae  cute
b     2      5    8    -3
c     3      6    9    -3
d    -2     -2   -2     0

In [ ]:
df

Hong  Hyeok  Jae  cute
a     1      4    7    -3
b     2      5    8    -3
c     3      6    9    -3
d    -2     -2   -2     0

In [ ]:
df['cute'] = df['cute'] + 10000
df

Hong  Hyeok  Jae   cute
a     1      4    7   9997
b     2      5    8   9997
c     3      6    9   9997
d    -2     -2   -2  10000

In [ ]:
cond = df['Hyeok'] > 4.5
cond

a    False
b     True
c     True
d    False
Name: Hyeok, dtype: bool

In [ ]:
df['great'] = df['cute'].shift(1)
df

Hong  Hyeok  Jae   cute   great
a     1      4    7   9997     NaN
b     2      5    8   9997  9997.0
c     3      6    9   9997  9997.0
d    -2     -2   -2  10000  9997.0

In [ ]:
df_trans = df.T
df_trans

a       b       c        d
Hong      1.0     2.0     3.0     -2.0
Hyeok     4.0     5.0     6.0     -2.0
Jae       7.0     8.0     9.0     -2.0
cute   9997.0  9997.0  9997.0  10000.0
great     NaN  9997.0  9997.0   9997.0

In [ ]:
df # df is not transposed

Hong  Hyeok  Jae   cute   great
a     1      4    7   9997     NaN
b     2      5    8   9997  9997.0
c     3      6    9   9997  9997.0
d    -2     -2   -2  10000  9997.0

In [ ]:
df.sort_index(0)

<ipython-input-62-3b0cb649c4c8>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.sort_index will be keyword-only.
  df.sort_index(0)


Hong  Hyeok  Jae   cute   great
a     1      4    7   9997     NaN
b     2      5    8   9997  9997.0
c     3      6    9   9997  9997.0
d    -2     -2   -2  10000  9997.0

In [ ]:
df.sort_values(['Hong'])

Hong  Hyeok  Jae   cute   great
d    -2     -2   -2  10000  9997.0
a     1      4    7   9997     NaN
b     2      5    8   9997  9997.0
c     3      6    9   9997  9997.0

In [ ]:
df['Hong'].unique

<bound method Series.unique of a    1
b    2
c    3
d   -2
Name: Hong, dtype: int64>

In [ ]:
df.isin([-1,-2])

Hong  Hyeok    Jae   cute  great
a  False  False  False  False  False
b  False  False  False  False  False
c  False  False  False  False  False
d   True   True   True  False  False

In [ ]:
df.count()

Hong     4
Hyeok    4
Jae      4
cute     4
great    3
dtype: int64

In [ ]:
df.max()

Hong         3.0
Hyeok        6.0
Jae          9.0
cute     10000.0
great     9997.0
dtype: float64

In [ ]:
df.min()

Hong       -2.0
Hyeok      -2.0
Jae        -2.0
cute     9997.0
great    9997.0
dtype: float64

In [ ]:
df.describe()

Hong     Hyeok       Jae      cute   great
count  4.000000  4.000000  4.000000      4.00     3.0
mean   1.000000  3.250000  5.500000   9997.75  9997.0
std    2.160247  3.593976  5.066228      1.50     0.0
min   -2.000000 -2.000000 -2.000000   9997.00  9997.0
25%    0.250000  2.500000  4.750000   9997.00  9997.0
50%    1.500000  4.500000  7.500000   9997.00  9997.0
75%    2.250000  5.250000  8.250000   9997.75  9997.0
max    3.000000  6.000000  9.000000  10000.00  9997.0

## Lab
use pandas methods

### 1

In [11]:
import pandas as pd
import numpy as np

s = pd.Series(index = ['hin pun', 'mangkon', 'nyon', 'noa'], data=[1230, 1780, 1560, 1320])
s

hin pun    1230
mangkon    1780
nyon       1560
noa        1320
dtype: int64

In [16]:
print(s.index)

Index(['hin pun', 'mangkon', 'nyon', 'noa'], dtype='object')


In [18]:
print(s.values)

[1230 1780 1560 1320]


In [19]:
cond = s > 1500
cond

hin pun    False
mangkon     True
nyon        True
noa        False
dtype: bool

In [20]:
print(s[cond])

mangkon    1780
nyon       1560
dtype: int64


### 2

In [21]:
import pandas as pd
import numpy as np

a = {'hin pun':[1230, 'Hong', 'M'], 'mangkon':[1780, 'U', 'M'], 'nyon':[1560, 'Im', 'F'], 'noa':[1320,'Lee', 'F']}
b = ['a','b','c']

df = pd.DataFrame(a,b)
df

hin pun mangkon  nyon   noa
a    1230    1780  1560  1320
b    Hong       U    Im   Lee
c       M       M     F     F

In [23]:
df.columns

Index(['hin pun', 'mangkon', 'nyon', 'noa'], dtype='object')

In [24]:
df.values

array([[1230, 1780, 1560, 1320],
       ['Hong', 'U', 'Im', 'Lee'],
       ['M', 'M', 'F', 'F']], dtype=object)

In [27]:
cond = df.loc['a'] > 1500
cond

hin pun    False
mangkon     True
nyon        True
noa        False
Name: a, dtype: bool

In [32]:
df.loc['a']

hin pun    1230
mangkon    1780
nyon       1560
noa        1320
Name: a, dtype: object

In [33]:
df.loc['a'][cond]

mangkon    1780
nyon       1560
Name: a, dtype: object

In [35]:
df[df.loc['a'][cond].index]

mangkon  nyon
a    1780  1560
b       U    Im
c       M     F

In [37]:
df.T

a     b  c
hin pun  1230  Hong  M
mangkon  1780     U  M
nyon     1560    Im  F
noa      1320   Lee  F

In [38]:
df.describe()

hin pun  mangkon  nyon   noa
count         3        3     3     3
unique        3        3     3     3
top        1230     1780  1560  1320
freq          1        1     1     1

## Lab
analyze public data

## Lab
make number baseball game

In [ ]:
import pandas as pd
import numpy as np
import random

